var wordsBank = {
    ar: [
        { word: "اسد", hidden: "ا_د", missingLetter: "س", options: ["س", "ش", "ص", "د"], emoji: "🦁" },
        { word: "كتاب", hidden: "كـ_اب", missingLetter: "ت", options: ["ب", "ت", "ث", "م"], emoji: "📚" },
        { word: "قلم", hidden: "قـ_م", missingLetter: "ل", options: ["ر", "ن", "ل", "ب"], emoji: "✏️" },
        { word: "تفاح", hidden: "تـ_اح", missingLetter: "ف", options: ["ق", "ف", "ث", "ص"], emoji: "🍎" },
        { word: "بيت", hidden: "بـ_ت", missingLetter: "ي", options: ["و", "ي", "ت", "ن"], emoji: "🏠" },
        { word: "موز", hidden: "مـ_ز", missingLetter: "و", options: ["و", "ي", "ا", "ل"], emoji: "🍌" },
        { word: "قط", hidden: "قـ_", missingLetter: "ط", options: ["ت", "د", "ط", "ظ"], emoji: "🐱" },
        { word: "شمس", hidden: "شـ_س", missingLetter: "م", options: ["ن", "م", "ل", "ب"], emoji: "☀️" },
        { word: "قمر", hidden: "قـ_ر", missingLetter: "م", options: ["م", "ن", "ت", "ب"], emoji: "🌙" },
        { word: "ولد", hidden: "و_د", missingLetter: "ل", options: ["ر", "ز", "ل", "ن"], emoji: "👦" },
        { word: "بنت", hidden: "بـ_ت", missingLetter: "ن", options: ["ت", "ن", "م", "ب"], emoji: "👧" },
        { word: "شجرة", hidden: "شـ_رة", missingLetter: "ج", options: ["ح", "ج", "خ", "م"], emoji: "🌳" },
        { word: "زهرة", hidden: "ز_رة", missingLetter: "ه", options: ["ه", "ع", "ح", "خ"], emoji: "🌸" },
        { word: "جمل", hidden: "جـ_ل", missingLetter: "م", options: ["م", "ن", "ل", "ب"], emoji: "🐫" },
        { word: "سمكة", hidden: "sـ_كة", missingLetter: "م", options: ["ن", "م", "ل", "ب"], emoji: "🐟" },
        { word: "كرة", hidden: "ك_ة", missingLetter: "ر", options: ["د", "ذ", "ر", "ز"], emoji: "⚽" },
        { word: "ساعة", hidden: "سـ_عة", missingLetter: "ا", options: ["ا", "و", "ي", "ل"], emoji: "⏰" },
        { word: "حليب", hidden: "حـ_يب", missingLetter: "ل", options: ["ر", "ن", "ل", "ب"], emoji: "🥛" },
        { word: "خبز", hidden: "خـ_ز", missingLetter: "ب", options: ["ت", "ث", "ب", "ن"], emoji: "🍞" },
        { word: "جبن", hidden: "جـ_ن", missingLetter: "ب", options: ["ن", "ب", "م", "ت"], emoji: "🧀" }
    ],
    en: [
        { word: "APPLE", hidden: "A_PLE", missingLetter: "P", options: ["B", "D", "P", "T"], emoji: "🍎" },
        { word: "CAT", hidden: "C_T", missingLetter: "A", options: ["E", "O", "A", "I"], emoji: "🐱" },
        { word: "DOG", hidden: "DO_", missingLetter: "G", options: ["C", "G", "K", "D"], emoji: "🐶" },
        { word: "BOOK", hidden: "B_OK", missingLetter: "O", options: ["A", "E", "O", "U"], emoji: "📖" },
        { word: "BALL", hidden: "B_LL", missingLetter: "A", options: ["A", "O", "E", "I"], emoji: "⚽" },
        { word: "SUN", hidden: "S_N", missingLetter: "U", options: ["A", "E", "O", "U"], emoji: "☀️" },
        { word: "MOON", hidden: "M_ON", missingLetter: "O", options: ["A", "E", "O", "U"], emoji: "🌙" },
        { word: "BOY", hidden: "B_Y", missingLetter: "O", options: ["A", "E", "O", "I"], emoji: "👦" },
        { word: "GIRL", hidden: "G_RL", missingLetter: "I", options: ["A", "E", "O", "I"], emoji: "👧" },
        { word: "FISH", hidden: "FI_H", missingLetter: "S", options: ["C", "S", "Z", "X"], emoji: "🐟" },
        { word: "BIRD", hidden: "B_RD", missingLetter: "I", options: ["A", "E", "O", "I"], emoji: "🐦" },
        { word: "MILK", hidden: "M_LK", missingLetter: "I", options: ["A", "E", "O", "I"], emoji: "🥛" },
        { word: "DOOR", hidden: "D_OR", missingLetter: "O", options: ["A", "E", "O", "U"], emoji: "🚪" },
        { word: "STAR", hidden: "ST_R", missingLetter: "A", options: ["A", "E", "O", "U"], emoji: "⭐" },
        { word: "CAR", hidden: "C_R", missingLetter: "A", options: ["A", "E", "O", "U"], emoji: "🚗" },
        { word: "BIKE", hidden: "B_KE", missingLetter: "I", options: ["A", "E", "O", "I"], emoji: "🚲" },
        { word: "PEN", hidden: "P_N", missingLetter: "E", options: ["A", "E", "O", "U"], emoji: "✏️" },
        { word: "HAND", hidden: "H_ND", missingLetter: "A", options: ["A", "E", "O", "U"], emoji: "✋" },
        { word: "FOOT", hidden: "F_OT", missingLetter: "O", options: ["A", "E", "O", "U"], emoji: "👣" },
        { word: "HOME", hidden: "H_ME", missingLetter: "O", options: ["A", "E", "O", "U"], emoji: "🏠" }
    ]
};
